[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo", "php82Extensions.pdo_mysql"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t back_end/api"
